CHUNK_SIZE = 16
RENDER_DISTANCE = 8
SPRITE_RENDER_DISTANCE = 2 # New: Separate render distance for sprites
BLOCK_HEIGHT = 20
WORLD_SEED = 42

# Sprite generation parameters
SPRITE_NOISE_SCALE = 0.05
SPRITE_NOISE_THRESHOLD = 0.70
SPRITE_HEIGHT_OFFSET = 0.5