CHUNK_SIZE = 16
RENDER_DISTANCE = 8
SPRITE_RENDER_DISTANCE = 4 # New: Separate render distance for sprites
BLOCK_HEIGHT = 20
WORLD_SEED = 42

# Sprite generation parameters
SPRITE_NOISE_SCALE = 0.05
SPRITE_NOISE_THRESHOLD = 0.80
SPRITE_HEIGHT_OFFSET = 0.5

# Animal generation parameters
ANIMAL_HEIGHT_OFFSET = 0.5
ANIMAL_RENDER_DISTANCE = 4

# Minimap
MINIMAP_RADIUS = 32
MINIMAP_CHUNK_PIXEL_SIZE = 8